### ISSUE TITLE
Checklist for v0.4.0 "Giratikanon"

### ISSUE THREAD

**Issue by mbloch** [mbloch/mapshaper#155]
Checklist for v0.4.0 release
- [x] Change some argument names (#119)
- [x] Allow multiple datasets in the cli (#95)
- [x] Make `-o force` the default behavior
- [x] Add `-o extension=` option to set Geo/TopoJSON  filename extension (#142)

Removed from the list:
- [ ] Support height/z-axis vertex data and Z- and M-type Shapefiles
- [ ] Command line generator for GUI (#33)

**Comment by mbloch** [comment]
v0.4 "Giratikanon" is published :)
